name: dotfiles
version: 1.0.0
backup:
  target: ../../data/
  home:
    - .config/git/
    - .config/go/
    # - .oh-my-zsh/custom/
  ignore:
    - .config/git/config
  encrypt:
    - .config/
encrypt:
  template: AES256_GCM
  key_path: "s3://devel/dotfiles/keyset.json"
  pass_path: "s3://devel/dotfiles/passphrase"
  masterkeyuri: ""
